apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: golf-ai

# For demo, you can patch image names or replicas here
# patches:
#   - target:
#       kind: Deployment
#       name: golf-backend
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/image
#         value: myregistry.azurecr.io/golf-swing-ai-backend:latest
